#pragma once

#define CONFIG_AGENTGUARD_NUTTX 1
#define CONFIG_IDF_TARGET_ESP32 0
#define CONFIG_IDF_TARGET_ESP32S2 0
#define CONFIG_IDF_TARGET_ESP32S3 1
#define CONFIG_IDF_TARGET_ESP32P4 0
#define CONFIG_SPIRAM 1
#define CONFIG_SPIRAM_SUPPORT 1
#define CONFIG_SPIRAM_RODATA 0
#define CONFIG_SPIRAM_XIP_FROM_PSRAM 0
#define CONFIG_ESP32P4_BOOST 0

/* After release preprocessing was restored, isolate all remaining optimized
 * operators behind a complete portable-C diagnostic backend. */
#define CONFIG_AGENTGUARD_ESP_DL_FORCE_C 1
#define CONFIG_AGENTGUARD_ESP_DL_FORCE_C_CONV 1
#define CONFIG_AGENTGUARD_ESP_DL_FORCE_C_DEPTHWISE 1
#define CONFIG_AGENTGUARD_FACE_SCORE_THRESHOLD_PERCENT 50

#define CONFIG_HUMAN_FACE_DETECT_MODEL_IN_FLASH_RODATA 1
#define CONFIG_HUMAN_FACE_DETECT_MODEL_IN_FLASH_PARTITION 0
#define CONFIG_HUMAN_FACE_DETECT_MODEL_IN_SDCARD 0
#define CONFIG_HUMAN_FACE_DETECT_MODEL_LOCATION 0
#define CONFIG_DEFAULT_HUMAN_FACE_DETECT_MODEL 0
#define CONFIG_FLASH_HUMAN_FACE_DETECT_MSRMNP_S8_V1 1
