#!/usr/bin/env bash

set -euo pipefail

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
openvela_root=${OPENVELA_ROOT:-}
if [[ -z "$openvela_root" ]]; then
  openvela_root=$(CDPATH= cd -- "$repo_root/.." && pwd)
  if [[ ! -f "$openvela_root/nuttx/.config" &&
        -f "$repo_root/../../../nuttx/.config" ]]; then
    openvela_root=$(CDPATH= cd -- "$repo_root/../../.." && pwd)
  fi
fi
config_file="$openvela_root/nuttx/.config"
tweak="$openvela_root/prebuilts/build-tools/linux-x86_64/bin/kconfig-tweak"
camera_patch="$repo_root/tools/patches/nuttx-esp32s3-cam-vsync.patch"
server_ipv4=${AGENTGUARD_SERVER_IPV4:-}
token_file=${AGENTGUARD_TOKEN_FILE:-}

if [[ ! -f "$config_file" ]]; then
  echo "Missing $config_file; configure the official ESP32-S3-EYE BSP first." >&2
  exit 1
fi

if [[ ! -x "$tweak" ]]; then
  echo "Missing executable kconfig-tweak: $tweak" >&2
  exit 1
fi

# Starting a capture must wait for the sensor's next real VSYNC edge.  The
# older ESP32-S3 CAM lower half flips the GPIO-matrix polarity on every frame,
# synthesizing an edge in the middle of a sensor frame and leaving a moving
# black band in the zero-initialized DMA buffer.  Apply the tested deletion
# once while preserving every other local NuttX change.
if git -C "$openvela_root/nuttx" apply --reverse --check "$camera_patch" \
    >/dev/null 2>&1; then
  echo "AgentGuard ESP32-S3 CAM VSYNC fix already applied"
elif git -C "$openvela_root/nuttx" apply --check "$camera_patch"; then
  git -C "$openvela_root/nuttx" apply "$camera_patch"
  echo "Applied AgentGuard ESP32-S3 CAM VSYNC fix"
else
  echo "Cannot apply ESP32-S3 CAM VSYNC fix cleanly: $camera_patch" >&2
  exit 1
fi

"$tweak" --file "$config_file" --enable \
  LVX_USE_DEMO_CONTEST2026_123_AGENTGUARD
"$tweak" --file "$config_file" --enable AGENTGUARD_ESP_DL
"$tweak" --file "$config_file" --disable LIBCXXNONE
"$tweak" --file "$config_file" --enable LIBCXXTOOLCHAIN
"$tweak" --file "$config_file" --disable HAVE_CXXINITIALIZE
"$tweak" --file "$config_file" --disable LIBMINIABI
"$tweak" --file "$config_file" --enable LIBSUPCXX_TOOLCHAIN
"$tweak" --file "$config_file" --set-val TLS_NELEM 4

# ESP-DL requires the GNU C++ runtime.  The board defconfig also enables two
# unrelated iperf implementations, one of which is a C++ application built
# against NuttX's libcxx compatibility headers.  That application conflicts
# with the selected GNU runtime and is not part of the AgentGuard product.
"$tweak" --file "$config_file" --disable UTILS_IPERF2
"$tweak" --file "$config_file" --disable NETUTILS_IPERF
"$tweak" --file "$config_file" --disable LIBYUV
"$tweak" --file "$config_file" --disable EXAMPLES_LVGLDEMO
"$tweak" --file "$config_file" --disable GRAPHICS_LVGL

# AgentGuard is the product entry point.  It initializes the required board
# devices itself and keeps the LCD diagnostics available throughout startup.
"$tweak" --file "$config_file" --set-str INIT_ENTRYPOINT agentguard_main
"$tweak" --file "$config_file" --set-val INIT_STACKSIZE 16384
"$tweak" --file "$config_file" --disable ETC_ROMFS

# OV2640 XCLK is generated by LEDC channel 0.  The BSP default channel pin is
# GPIO2, but ESP32-S3-EYE connects camera XCLK to GPIO15.
"$tweak" --file "$config_file" --set-val ESP32S3_LEDC_CHANNEL0_PIN 15

# ESP32-S3-EYE's MENU, PLAY, UP+ and DN- keys share the GPIO1/ADC1_CH0
# resistor ladder.  The application registers /dev/adc0 directly and keeps
# the existing GPIO0 BOOT device as a fallback.  The board defconfig also
# assigns GPIO1 to SPI2 MISO, but the ST7789 connection is write-only.  Leave
# MISO disconnected so the display bus cannot retain the ADC button pin.
"$tweak" --file "$config_file" --enable ADC
"$tweak" --file "$config_file" --enable ESP32S3_ADC
"$tweak" --file "$config_file" --enable ESP32S3_ADC1_CHANNEL0
"$tweak" --file "$config_file" --enable ESP32S3_ADC_VOL_3100
"$tweak" --file "$config_file" --set-val ESP32S3_SPI2_MISOPIN -1

# The ST7789 frame is 115,200 bytes.  Polling SPI splits it into roughly 1,800
# 64-byte transactions and visibly scans the LCD.  Use the existing SPI2 DMA
# path; the display worker cleans its cached transmit buffer before submission.
"$tweak" --file "$config_file" --enable ESP32S3_SPI_DMA
"$tweak" --file "$config_file" --set-val ESP32S3_SPI_DMA_BUFSIZE 15360
"$tweak" --file "$config_file" --set-val ESP32S3_SPI_DMATHRESHOLD 64
# Match Espressif's ESP32-S3-EYE BSP: the board-qualified ST7789 link runs at
# 80 MHz, halving each synchronous scan-out interval versus the 40 MHz default.
"$tweak" --file "$config_file" --set-val LCD_ST7789_FREQUENCY 80000000

# AgentGuard uses Wi-Fi but does not use Bluetooth.  On the tested board the
# BLE HCI startup work item intermittently panicked in hpwork, so keep the
# unused controller and Wi-Fi/BT coexistence path disabled for this product.
"$tweak" --file "$config_file" --disable ESP32S3_BLE
"$tweak" --file "$config_file" --disable ESPRESSIF_BLE
"$tweak" --file "$config_file" --disable ESP32S3_WIFI_BT_COEXIST

# The current ESP32-S3 SMP SPI-flash guard can start its per-CPU blocking
# threads before their affinities are installed.  On the tested board this
# leaves spiflash_start() waiting forever during the first LittleFS access.
# AgentGuard does not require two cores, so use the stable uniprocessor path.
"$tweak" --file "$config_file" --disable SMP
"$tweak" --file "$config_file" --set-val SMP_NCPUS 1

# ESP32-S3 exposes its AI vector instructions as coprocessor 3.  ESP-DL's
# optimized kernels and official model parser use those instructions, while
# the board default enables only coprocessor 0 (FPU).  Enable both CP0 and CP3
# for all AgentGuard threads; otherwise the first model parameter construction
# raises EXCCAUSE_CP3_DISABLED (0x23).
"$tweak" --file "$config_file" --set-val XTENSA_CP_INITSET 0x0009

# The Xtensa separate internal heap also redirects every task stack into a
# 96 KiB pool.  On this board's flat startup path, initial task creation then
# produces an invalid scheduler context before the LCD task can start.  Keep
# it disabled; ESP-DL operator staging must not depend on this global switch.
"$tweak" --file "$config_file" --disable XTENSA_IMEM_USE_SEPARATE_HEAP

# Use the last 1 MiB of the configured 4 MiB flash address space for the
# official ESP32-S3 board LittleFS mount at /mnt/spif.  Keeping the partition
# at 0x300000 leaves 3 MiB for the simple-boot firmware image.
"$tweak" --file "$config_file" --enable ESP32S3_SPIFLASH
"$tweak" --file "$config_file" --enable ESP32S3_MTD
"$tweak" --file "$config_file" --enable MTD
"$tweak" --file "$config_file" --enable MTD_BYTE_WRITE
"$tweak" --file "$config_file" --enable MTD_PARTITION
"$tweak" --file "$config_file" --set-val FTL_USLEEP 0
"$tweak" --file "$config_file" --set-val ESP32S3_SPIFLASH_MTD_BLKSIZE 256
"$tweak" --file "$config_file" --set-val \
  ESP32S3_SPIFLASH_OP_TASK_STACKSIZE 768
"$tweak" --file "$config_file" --disable ESP32S3_SPIFLASH_SMARTFS
"$tweak" --file "$config_file" --disable ESP32S3_SPIFLASH_NXFFS
"$tweak" --file "$config_file" --disable ESP32S3_SPIFLASH_SPIFFS
"$tweak" --file "$config_file" --enable ESP32S3_SPIFLASH_LITTLEFS
"$tweak" --file "$config_file" --enable FS_LITTLEFS
"$tweak" --file "$config_file" --set-val FS_LITTLEFS_PROGRAM_SIZE_FACTOR 4
"$tweak" --file "$config_file" --set-val FS_LITTLEFS_READ_SIZE_FACTOR 4
"$tweak" --file "$config_file" --set-val FS_LITTLEFS_BLOCK_SIZE_FACTOR 1
"$tweak" --file "$config_file" --set-val FS_LITTLEFS_CACHE_SIZE_FACTOR 4
"$tweak" --file "$config_file" --set-val FS_LITTLEFS_LOOKAHEAD_SIZE 0
"$tweak" --file "$config_file" --set-val FS_LITTLEFS_BLOCK_CYCLE 200
"$tweak" --file "$config_file" --set-val FS_LITTLEFS_NAME_MAX 48
"$tweak" --file "$config_file" --set-val FS_LITTLEFS_FILE_MAX 2147483647
"$tweak" --file "$config_file" --set-val FS_LITTLEFS_ATTR_MAX 1022
"$tweak" --file "$config_file" --enable FS_LITTLEFS_ATTR_UPDATE
"$tweak" --file "$config_file" --set-val ESP32S3_STORAGE_MTD_OFFSET 0x300000
"$tweak" --file "$config_file" --set-val ESP32S3_STORAGE_MTD_SIZE 0x100000
"$tweak" --file "$config_file" --set-str AGENTGUARD_LOG_PATH \
  /mnt/spif/agentguard-events.jsonl
"$tweak" --file "$config_file" --set-val AGENTGUARD_LOG_RETENTION_DAYS 7
"$tweak" --file "$config_file" --set-val AGENTGUARD_LOG_MAX_BYTES 524288

if [[ -n "$server_ipv4" ]]; then
  if [[ ! "$server_ipv4" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    echo "AGENTGUARD_SERVER_IPV4 is not an IPv4 address." >&2
    exit 1
  fi

  IFS=. read -r octet1 octet2 octet3 octet4 <<< "$server_ipv4"
  for octet in "$octet1" "$octet2" "$octet3" "$octet4"; do
    if ((10#$octet > 255)); then
      echo "AGENTGUARD_SERVER_IPV4 contains an invalid octet." >&2
      exit 1
    fi
  done

  "$tweak" --file "$config_file" --set-str \
    AGENTGUARD_SERVER_IPV4 "$server_ipv4"
fi

if [[ -n "$token_file" ]]; then
  if [[ ! -f "$token_file" ]]; then
    echo "AGENTGUARD_TOKEN_FILE does not exist." >&2
    exit 1
  fi

  shared_token=$(<"$token_file")
  if ((${#shared_token} < 16)); then
    echo "AgentGuard shared token must contain at least 16 characters." >&2
    exit 1
  fi

  "$tweak" --file "$config_file" --set-str \
    AGENTGUARD_SHARED_TOKEN "$shared_token"
  unset shared_token
fi

make -C "$openvela_root/nuttx" include/nuttx/config.h

echo "AgentGuard configuration applied to $config_file"
if [[ -n "$server_ipv4" ]]; then
  echo "PC agent address configured: $server_ipv4"
fi
if [[ -n "$token_file" ]]; then
  echo "Shared token configured from file (value not displayed)"
fi
